version: "2.1"
services:

        
        vendor:
                build:
                        context: ./vendor
                volumes:
                        - ../backend/:/var/www

        nextjs:
                build:
                        context: ./nextjs
                volumes:
                        - ../frontend/:/var/www
