version: "2.1"
services:

        #assets:
        #        build:
        #                context: ./assets
        #        volumes:
        #                - ../backend/:/var/www

        vendor:
                build:
                        context: ./vendor
                volumes:
                        - ../backend/:/var/www

        nextjs:
                build:
                        context: ./nextjs
                volumes:
                        - ../frontend/:/var/www
