version: "2.1"
services:

        database:
                restart: unless-stopped
                image: linuxserver/mariadb
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Paris
                        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
                        - MYSQL_DATABASE=${DATABASE_NAME}
                        - MYSQL_USER=${DATABASE_USER}
                        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
                ports:
                        - "3306:3306"
                volumes:
                        - ./database/data/:/config

        php-fpm:
                restart: unless-stopped
                build:
                        context: ./php-fpm
                depends_on:
                        - database
                environment:
                        - APP_ENV=${APP_ENV}
                        - APP_SECRET=${APP_SECRET}
                        - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.4.10
                        - SECURE_SCHEME=https
                volumes:
                        - ../backend/:/var/www

        nextjs:
                restart: unless-stopped
                build:
                        context: ./nextjs
                depends_on:
                        - php-fpm
                environment:
                        - SERVEUR_URL=https://benjamintrubert.fr
                        - MAIL_USER=contact@benjamintrubert.fr
                        - MAIL_PASSWORD=Salem_Vyk1808
                volumes:
                        - ../frontend/:/var/www

        nginx:
                restart: unless-stopped
                build:
                           context: ./nginx
                depends_on:
                        - php-fpm
                        - nextjs
                volumes:
                        - ../backend/:/var/www
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/sites/:/etc/nginx/sites-available
                        - ./nginx/conf.d/:/etc/nginx/conf.d
                        - ./nginx/ssl/:/etc/ssl
                        - ./logs:/var/log
                ports:
                        - "80:80"
                        - "443:443"
